### ISSUE TITLE
FileNotFoundError : No such file or directory: '.../ColorSchemes/Print-Color'

### ISSUE THREAD

**Issue by lkuty** [facelessuser/ExportHtml#74]
I have ST3 version 3.2.2 build 3211. I have ExportHtml version 2.14.3. It worked with a previous version. But since a few weeks, everytime I want to Browser Print - Color or Grayscale, I have a FileNotFound error. I guess there may be a problem with paths. I don't know if it could be filed as a bug.

````
Traceback (most recent call last):
  File "/Users/ludo/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package/lib/color_scheme_matcher.py", line 402, in __init__
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ludo/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package/ExportHtml.py", line 285, in execute
  File "/Users/ludo/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package/ExportHtml.py", line 985, in run
  File "/Users/ludo/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package/ExportHtml.py", line 457, in setup
  File "/Users/ludo/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package/lib/color_scheme_matcher.py", line 405, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ludo/Library/Application Support/Sublime Text 3/Packages/ExportHtml/ColorSchemes/Print-Color'
````

````
$ pwd
/Users/ludo/Library/Application Support/Sublime Text 3/Installed Packages
ludo@m in ~/Library/Application Support/Sublime Text 3/Installed Packages
$ ls -l ExportHtml.sublime-package
-rw-r--r--  1 ludo  staff  320577 Jan 28 13:11 ExportHtml.sublime-package
````

````
$ pwd
/Users/ludo/Library/Application Support/Sublime Text 3/Packages/User
ludo@m in ~/Library/Application Support/Sublime Text 3/Packages/User
$ ls -l ExportHtml.sublime-settings
-rw-r--r--@ 1 ludo  staff  32 Jan 28 11:30 ExportHtml.sublime-settings
````

````
ludo@m in ~/Library/Application Support/Sublime Text 3/Packages
$ ls -l
total 0
drwxr-xr-x    3 ludo  staff    96 Mar 21  2019 AddTrailingSpaces
drwxr-xr-x   23 ludo  staff   736 Oct 12  2017 DA UI
drwxr-xr-x    3 ludo  staff    96 Nov  7 16:12 Default
drwxr-xr-x  110 ludo  staff  3520 Apr 23  2018 LaTeXTools
drwxr-xr-x   16 ludo  staff   512 Aug 28  2016 Print to HTML
drwxr-xr-x    3 ludo  staff    96 Sep 12  2015 PyV8
drwx------   68 ludo  staff  2176 Nov  7 13:17 User
drwxr-xr-x    9 ludo  staff   288 Mar 21  2018 backrefs
drwxr-xr-x    5 ludo  staff   160 Sep 27 17:31 markupsafe
drwxr-xr-x   14 ludo  staff   448 Nov 22 07:38 mdpopups
drwxr-xr-x    6 ludo  staff   192 Aug  4  2016 pygments
drwxr-xr-x    7 ludo  staff   224 Jan 15 06:41 pymdownx
drwxr-xr-x    5 ludo  staff   160 Sep 27 17:31 python-jinja2
drwxr-xr-x    6 ludo  staff   192 Nov 22 07:38 python-markdown
drwxr-xr-x    6 ludo  staff   192 Sep 27 17:31 pyyaml
drwxr-xr-x   11 ludo  staff   352 Jul 16  2017 shellenv
````

**Comment by facelessuser** [comment]
Can you post your personal ExportHtml settings?

**Comment by lkuty** [comment]
````
{
  "alternate_font_size": 12
}
````

**Comment by facelessuser** [comment]
Have you restarted Sublime since the package updated?

**Comment by lkuty** [comment]
Yes, I even reinstalled it to get the latest stable version. Previously I had the dev version. I also reinstalled the package.

**Comment by facelessuser** [comment]
I think I got confused and thought the package would figure out color scheme format automatically if extension want present. I thought I added that...

Anyways, when I tested, I was apparently testing my personal settings, not the default, so I missed this. For a work around, you can copy the HTML settings over to your personal, and add the extension of`.sublime-color-scheme` to the scheme file parameter.

That and apparently I replaced a day with a space in the default scheme names...

I'll get a fix it later today.

**Comment by lkuty** [comment]
OK, many thanks :-)

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: bug, S: confirmed

**Comment by facelessuser** [comment]
New version has been tagged: https://github.com/facelessuser/ExportHtml/releases/tag/st3-2.14.4

It may take an hour or two to pop up in Package Control, but when it does, you should have the fix.

**Comment by lkuty** [comment]
It works as expected. Thanks.
