### ISSUE TITLE
Bug feedback: The export menu cannot be displayed normally, in the default setting

### ISSUE THREAD

**Issue by orbwalker** [facelessuser/ExportHtml#90]
version: 2.17.3
os: windows 10 LTSC 1809 x86_64
-
Bug feedback: The export menu cannot be displayed normally, in the default setting
-
screenshot:
[https://ibb.co/zJSySXy](url)
[https://ibb.co/zQhhDJt](url)

**Comment by facelessuser** [comment]
I'll need you to open your Sublime Text console and look for errors. I know some of the dependencies have been updated, and most likely things didn't get updated properly. Before making suggestions, I'd like to confirm what kind of errors you are seeing in your Sublime console. I suspect you'll have to force an upgrade of your dependencies, which I can walk you through, but first I need to see what kind of errors Sublime is reporting.

**Comment by blake-regalia** [comment]
I can confirm this as well for ST4 (using v4114)

Here is relevant console error stack:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/blake/Library/Application Support/Sublime Text/Installed Packages/ExportHtml.sublime-package/ExportHtml.py", line 33, in <module>
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/blake/Library/Application Support/Sublime Text/Installed Packages/ExportHtml.sublime-package/lib/color_scheme_matcher.py", line 31, in <module>
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/blake/Library/Application Support/Sublime Text/Installed Packages/ExportHtml.sublime-package/lib/st_colormod.py", line 3, in <module>
  File "/Users/blake/Library/Application Support/Sublime Text/Packages/mdpopups/st3/mdpopups/__init__.py", line 13, in <module>
    from . import jinja2
  File "/Users/blake/Library/Application Support/Sublime Text/Packages/mdpopups/st3/mdpopups/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
ImportError: No module named 'jinja2'
```

**Comment by facelessuser** [comment]
Oh, I know what happened.

**Comment by facelessuser** [comment]
Dependencies were reduced as `mdpopups` vendors everything it needs now. We link to its vendored coloraide, and should also link to its vendored jinja2. This keeps our dependency just to `mdpopups`.

**Comment by facelessuser** [comment]
A new release has been tagged. It should be available within an hour or two on Package Control.

**Comment by blake-regalia** [comment]
Still getting the exact same error on v2.17.4, is this a dependency issue in mdpopups?

**Comment by facelessuser** [comment]
On a fresh install, 2.17.4 is working just fine:

<img width="912" alt="Screen Shot 2021-09-07 at 5 31 15 AM" src="https://user-images.githubusercontent.com/1055125/132405454-10ea5ecc-d634-47d1-8365-3deb0830b86b.png">

There is no issue anymore in mdpopups or ExportHTML. Can you select `Preferences->Package Settings->Export HTML->Support Info` and post what  you are getting?

I'm running:

```
- ST ver.: 4113
- Platform: osx
- Arch: x64
- Plugin ver.: 2.17.4
- Install via PC: True
- mdpopups ver.: 4.2.0
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1
```

**Comment by facelessuser** [comment]
Sorry, posted wrong screencap, updated.

**Comment by blake-regalia** [comment]
```
- ST ver.: 4114
- Platform: osx
- Arch: x64
- Plugin ver.: 2.17.4
- Install via PC: True
- mdpopups ver.: Version could not be acquired!
- markdown ver.: Version could not be acquired!
- pygments ver.: Version could not be acquired!
- jinja2 ver.: Version could not be acquired!
```

**Comment by facelessuser** [comment]
Yes it is. `mdpopups` is vendoring its packages, but it appears it is not referencing the vendored packages in some places.

**Comment by blake-regalia** [comment]
```
  File "/Users/blake/Library/Application Support/Sublime Text/Packages/mdpopups/st3/mdpopups/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
```

https://github.com/pallets/jinja/blob/2.10.x/jinja2/__init__.py#L33

I forget how python package resolution works, shouldn't this resolve to itself ok even within a vendored package?

**Comment by facelessuser** [comment]
No. I tested with non-vendored dependencies still installed, so I missed making Jinja2 relative to itself.

**Comment by facelessuser** [comment]
I'm testing in a clean environment now, so I should get everything worked out shortly.

**Comment by facelessuser** [comment]
Sorry it took so long.

Imessed up that last `mdpopups` release pretty good. The vendored package branch had sat there so long that I forgot I hadn't finished making all the packages relative yet, and it happened to work because I was testing on a system that had non-vendored packages...should be fixed in the latest release though (4.2.1). I had to test it in a clean install by itself. If packages using it still required the non-vendored packages (which I imagine most still do) they likely never noticed.

I'm not sure when Package Control will see the new release, but when it does, if it doesn't update automatically, you may need to delete the old `mdpopups` and run `Package Control: Satisfy dependencies`.

This time I ran completely clean with nothing else installed, now it is working proper. Sorry about the mess.

**Comment by facelessuser** [comment]
Seems package control now sees the latest mdpopups, so just update `Package Control: Satisfy dependencies` and check the console to see if it installs. Restart of ST probably required.

**Comment by blake-regalia** [comment]
Works now, thanks!
